FROM node:18.12
RUN apt-get -y install openssl

# ----------- Base ----------
WORKDIR /app/backend
COPY backend/package*.json backend/tsconfig*.json backend/yarn.lock ./
RUN yarn

# ----------- Backend ----------
WORKDIR /app/backend
COPY ./backend ./
# RUN npx prisma generate

EXPOSE 2030