FROM node:18.12
RUN apt-get -y install openssl

# ----------- Backend ----------
WORKDIR /app
COPY ./ ./
RUN rm -rf node_modules
RUN yarn

# RUN npx prisma generate

EXPOSE 2050
CMD ["npm", "run", "dev"]